Code.require_file("/tmp/llama_review/_common.exs")
m = EdgeCase.model()
{:ok, ctx} = LlamaCppEx.Context.create(m, n_ctx: 1024)
{:ok, tokens} = LlamaCppEx.Tokenizer.encode(m, "Hello world")
:ok = LlamaCppEx.NIF.decode(ctx.ref, tokens)
pos_before = LlamaCppEx.NIF.memory_seq_pos_max(ctx.ref, 0)
_ = LlamaCppEx.NIF.context_can_seq_rm(ctx.ref)
pos_after = LlamaCppEx.NIF.memory_seq_pos_max(ctx.ref, 0)
IO.puts("RESULT[side_effect]: pos_before=#{pos_before} pos_after=#{pos_after}")
